# .github/workflows/deploy-production.yml
name: Deploy (production on release)

on:
  release:
    # 'released' only fires when a prerelease is promoted to a full release
    # or when you publish a normal release directly.
    types: [released]

permissions:
  contents: read

jobs:
  call:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-engine.yml
    with:
      env_name: production
    secrets: inherit
