name: Deploy (production on release)

on:
  release:
    types: [released]  # won't trigger on prerelease

permissions:
  contents: read

jobs:
  call:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-engine.yml
    with:
      env_name: production
    secrets: inherit
