# .github/workflows/deploy-production.yml
name: Deploy (production on release)
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write # REQUIRED for OIDC/WIF

jobs:
  call:
    # make sure pre-releases don’t trigger prod
    if: ${{ !github.event.release.prerelease }}
    uses: ./.github/workflows/deploy-engine.yml
    with:
      env_name: production
