# .github/workflows/deploy-staging.yml
name: Deploy (staging on pre-release)
on:
  release:
    types: [prereleased]

permissions:
  contents: read
  id-token: write

jobs:
  call:
    if: ${{ github.event.release.prerelease }}   # guard
    uses: ./.github/workflows/deploy-engine.yml
    with:
      env_name: staging
