# .github/workflows/deploy-staging.yml
on:
  release:
    types: [prereleased]
permissions:
  contents: read
jobs:
  call:
    if: ${{ github.event.release.prerelease }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-engine.yml
    with:
      env_name: staging
    secrets: inherit
