# .github/workflows/deploy-staging.yml
name: Deploy (staging on pre-release)
on:
  release:
    types: [prereleased]

permissions:
  contents: read  # no id-token

jobs:
  call:
    if: ${{ github.event.release.prerelease }}
    uses: ./.github/workflows/deploy-engine.yml   # same-repo path; no @sha
    with:
      env_name: staging
