# .github/workflows/deploy-production.yml
name: Deploy (production on release)
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  call:
    if: ${{ !github.event.release.prerelease }}  # don't run for pre-releases
    uses: ./.github/workflows/deploy-engine.yml
    with:
      env_name: production
