name: Deploy (staging on pre-release)
on:
  release:
    types: [prereleased]

# top-level is recommended
permissions:
  contents: read
  id-token: write

jobs:
  call-workflow:
    if: ${{ github.event.release.prerelease }}
    uses: ./.github/workflows/deploy-engine.yml   # same-repo: use relative path
    permissions:                      # belt & suspenders (ok to keep)
      contents: read
      id-token: write
    with:
      env_name: staging
